### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ahmad-baba** [Santosl2/wpp-chatgpt#8]
Whenever I run the npm the below error message appears 

```
> wpp-chatgpt@1.0.0 start
> node src/index.mjs run

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                   ┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 2.1.6                                                                                  ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:7001
- Initializing WA
/Users/ahmadbaba/Desktop/whatsappchatgpt/wpp-chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (/Users/ahmadbaba/Desktop/whatsappchatgpt/wpp-chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at ChromeLauncher.launch (/Users/ahmadbaba/Desktop/whatsappchatgpt/wpp-chatgpt/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:92:36)
    at async PuppeteerExtra.launch (/Users/ahmadbaba/Desktop/whatsappchatgpt/wpp-chatgpt/node_modules/puppeteer-extra/dist/index.cjs.js:128:25)

Node.js v18.16.0
```

**Comment by Santosl2** [comment]
Hello, did you fixed this?
